In [1]:
import pandas as pd
import sqlite3

In [2]:
con = sqlite3.connect("shop/test.db")

In [3]:
addproduct=pd.read_sql_query("SELECT * from addproduct", con)
brand=pd.read_sql_query("SELECT * from brand", con)
events=pd.read_sql_query("SELECT * from events", con)
specsvalues=pd.read_sql_query("SELECT * from specsvalues", con)
category=pd.read_sql_query("SELECT * from category", con)
subcategories=pd.read_sql_query("SELECT * from subcategories", con)
specs=pd.read_sql_query("SELECT * from specs", con)

In [4]:
cat_subcat=pd.merge(category,subcategories,how='left',left_on='id',right_on='category_id')
cat_subcat=cat_subcat[['category_id','name_x','id_y','name_y']]
cat_subcat.columns=['category_id','category','subcategory_id','subcategory']

In [5]:
product=pd.merge(addproduct,cat_subcat[['category','subcategory_id','subcategory']],how='left',on='subcategory_id')
product=product.drop(['image_1','image_2','image_3'],axis='columns')
product.head()

,id,name,price,discount,stock,colors,desc,pub_date,category_id,subcategory_id,brand_id,category,subcategory
0,1,Allen Solly Men's Plain Slim Fit Casual Shirt,699,0,25,"Blue, Purple, Black",Allen solly Mens Cotton Full sleeve Overdyed s...,2020-07-08 15:54:29.990947,1,2,8,Men's Clothing,Shirt
1,2,Park Avenue Men's Solid Slim Fit Formal Shirt,563,0,15,"White, Blue, Khaki",This classic shirt from Park Avenue is a versa...,2020-07-08 15:57:00.755305,1,2,11,Men's Clothing,Shirt
2,3,Park Avenue Men's Plain Slim Fit Formal Shirt,654,0,15,"White, Blue, Black",Be noticed at work by enhancing your looks wit...,2020-07-08 15:58:57.811980,1,2,11,Men's Clothing,Shirt
3,4,Wrangler Men's Relaxed Fit Jeans,1198,5,25,"Blue, Black",Wrangler is the everyday performance denim bra...,2020-07-08 16:02:12.713819,1,3,12,Men's Clothing,Jeans
4,5,Casio G-Shock Analog-Digital Blue Dial Men's W...,6396,0,25,"Blue, Black",Mineral Glass Magnetic Resistant Shock Resista...,2020-07-08 16:05:11.097813,1,4,13,Men's Clothing,Watch

In [8]:
specifications=pd.merge(specs[['id','name']],specsvalues[['product_id','spec_id']],left_on='id',right_on='spec_id')
specifications.drop('id',axis='columns')
specifications.head(6)

   id                          name  product_id  spec_id
0   1             Fit : Regular Fit           1        1
1   1             Fit : Regular Fit          31        1
2   1             Fit : Regular Fit          32        1
3   1             Fit : Regular Fit          33        1
4   1             Fit : Regular Fit          10        1
5   2  Sleeve Length : Long Sleeves           1        2

In [9]:
specifications['name'].unique()

array(['Fit : Regular Fit', 'Sleeve Length : Long Sleeves',
       'Material : Cotton', 'Collar : Button-Down Collar',
       'Pattern : Solid', 'Occasion : Formal', 'Collar : Spread Collar',
       'Fit : Slim Fit', 'Pattern : Textured', 'Occasion : Casual',
       'Pattern : Buffalo Checks', 'Pattern : Tartan Checks',
       'Neck : Round Neck', 'Pattern : Printed', 'Sleeves : Half Sleeves',
       'Collar : Mandarin Collar', 'Collar : Ainsley Collar',
       'Distress: Clean Look', 'Fade: Heavy Fade', 'Fit: Slim Fit',
       'Waist Rise: Mid-Rise', 'Length: Regular', 'Strech: Strechable',
       'Display: Analogue and Digital', 'Movement : Automatic',
       'Type: Hybrid', 'Features: Multi Function', 'Dial Shape: Round',
       'Dial Pattern: Round', 'Length: Short',
       'Number of Compartments: 2', 'Number of Slip Pockets: 1',
       'Material: Leather', 'Number of Card Holder: 4',
       'Toe Shape: Round Toe', 'Ankle Height: Mid Top',
       'Warranty: 2 months', 'Pattern: Solid', 'Sole Material: TPR',
       'Fastening: Lace Ups', 'Sport: Running', 'Outsole Type: Marking',
       'Material: Mesh', 'Ankle Height: Regular', 'Neck: Pollo Collar',
       'Sleeves Length: Three-Quarter Sleeves', 'Type: Peplum',
       'Transparency: Opaque', 'Print or Pattern Type: Self Design',
       'Length:Regular', 'Distress: Clean  Look', 'Fade: Light Fade',
       'Fit: Skinny Fit', 'Waistbend: With Belt Loops', 'Waist: Low-Rise',
       'Shade: Dark', 'Length: Cropped', 'Strech:  Strechable',
       'Top Fabric:Net| Bottom Fabric: Santoon | Dupatta Fabric: Net| Inner Fabric: Santoon',
       'Work: Embroidered', 'Sleeve: Full Sleeve', 'Neck: Round Neck',
       'Style: Anarkali Gown with Dupatta and Bottom', 'Size: Free Size',
       'Dial Color: Blue', ' Case Shape: Tonneau',
       ' Band Material: Patent Leather', 'Case Shape: Special',
       'water-resistant for up to 3 ATM', 'Watch Movement Type: Quartz',
       'Watch Display Type: Analog', 'Sport:  Running',
       'Fastening: Lace-Ups', 'Outsole Type: Non-Marking',
       'Pronation for Running Shoes: Neutral', 'Material:  Mesh',
       'Ankle Height:  Regular', 'Cleats: No Cleats', 'Arch Type: Medium',
       'Sleeve Length: Long Sleeves', 'Fit: Regular Fit',
       'Occasion: Casual', 'Hemline: Curved', 'Collar: Spread Collar',
       'Print or Pattern Type: Solid', 'Length:  Regular',
       'Distress:  Clean Look', 'Fade:  Light Fade', 'Fit:  Regular Fit',
       'Waistband:  With belt loops', 'Shade:  Medium',
       'Stretch:  Stretchable', 'Sleeve Length: No Sleeves',
       'Type: Regular', 'Lining: Has a lining', 'Neck: Shoulder Straps',
       'Print or Pattern Type:  Polka Dots', 'Transparency:  Opaque',
       'Type: Flatforms', 'Pattern: Printed', 'Shoe Width: Regular',
       'Insole: Comfort Insole', 'Toe Shape:  Round Toe',
       'Ankle Height:   Regular', 'Sole Material:  TPR',
       'Letter Recognition', 'Letter Sounds', 'Spelling',
       'Reading Skills'], dtype=object)

In [10]:
specs=pd.DataFrame(index=range(len(product)),columns=specifications['name'].unique())
specs['id']=product['id']
specs['price']=addproduct['price']
specs

,Fit : Regular Fit,Sleeve Length : Long Sleeves,Material : Cotton,Collar : Button-Down Collar,Pattern : Solid,Occasion : Formal,Collar : Spread Collar,Fit : Slim Fit,Pattern : Textured,Occasion : Casual,...,Insole: Comfort Insole,Toe Shape: Round Toe,Ankle Height: Regular,Sole Material: TPR,Letter Recognition,Letter Sounds,Spelling,Reading Skills,id,price
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,699
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,563
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,654
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1198
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,6396
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6496
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,1099
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,999
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,1599
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,585
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,385
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,585
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,1200
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,1399
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,575
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,625
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,799
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,1599
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,1199
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,1799
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,1599
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,566
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,566
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,1799
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,2499
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,495
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,1499
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,1200
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,213
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,599
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,649
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,649
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,350

In [11]:
spec_list=specifications.groupby('product_id')['name'].groups
for product in spec_list:
    for spec in spec_list[product]:
        specs.loc[specs[specs['id']==product].index,[specifications['name'][spec]]]=1        
        #print(product,spec)

In [12]:
specs.loc[specs[specs['id']==product].index,[specifications['name'][spec]]]

   Sleeves : Half Sleeves
32                      1

In [13]:
specs.fillna(0)

,Fit : Regular Fit,Sleeve Length : Long Sleeves,Material : Cotton,Collar : Button-Down Collar,Pattern : Solid,Occasion : Formal,Collar : Spread Collar,Fit : Slim Fit,Pattern : Textured,Occasion : Casual,...,Insole: Comfort Insole,Toe Shape: Round Toe,Ankle Height: Regular,Sole Material: TPR,Letter Recognition,Letter Sounds,Spelling,Reading Skills,id,price
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,699
1,0,1,1,1,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,2,563
2,0,1,1,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,3,654
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,4,1198
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,5,6396
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,6496
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,7,1099
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,8,999
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,9,1599
9,1,0,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,10,585
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,11,385
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,585
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,13,1200
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,14,1399
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,575
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,16,625
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,17,799
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,18,1599
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,19,1199
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,20,1799
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,21,1599
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,22,566
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,23,566
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,24,1799
24,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,25,2499
25,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,26,495
26,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,27,1499
27,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,28,1200
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,29,213
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,30,599
30,1,1,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,31,649
31,1,1,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,32,649
32,1,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,33,350

In [14]:
specs.index=specs['id']

In [15]:
specs=specs.drop('id',axis='columns').fillna(0)
specs

,Fit : Regular Fit,Sleeve Length : Long Sleeves,Material : Cotton,Collar : Button-Down Collar,Pattern : Solid,Occasion : Formal,Collar : Spread Collar,Fit : Slim Fit,Pattern : Textured,Occasion : Casual,...,Shoe Width: Regular,Insole: Comfort Insole,Toe Shape: Round Toe,Ankle Height: Regular,Sole Material: TPR,Letter Recognition,Letter Sounds,Spelling,Reading Skills,price
id,,,,,,,,,,,,,,,,,,,,,
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,699
2,0,1,1,1,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,563
3,0,1,1,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,654
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1198
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6396
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6496
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1099
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,999
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1599
10,1,0,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,585
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,385
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,585
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1200
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1399
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,575
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,625
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,799
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1599
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1199
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1799
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1599
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,566
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,566
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1799
25,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,2499
26,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,495
27,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,1499
28,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,1200
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,213
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,599
31,1,1,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,649
32,1,1,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,649
33,1,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,350

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(specs)[1]

array([0.99998945, 1.        , 0.99999552, 0.99998687, 0.99998888,
       0.99998889, 0.99998689, 0.99998595, 0.99998798, 0.99998626,
       0.99997209, 0.99998165, 0.99998618, 0.99998743, 0.99997837,
       0.99998128, 0.99998269, 0.99998759, 0.99998652, 0.99998788,
       0.99998778, 0.99997959, 0.99997959, 0.99998803, 0.9999884 ,
       0.99997671, 0.99998762, 0.99998687, 0.99994488, 0.99998338,
       0.99998731, 0.99998731, 0.99996954])

In [129]:
specifications[specifications['product_id']==2]

    id                          name  product_id  spec_id
8    2  Sleeve Length : Long Sleeves           2        2
13   3             Material : Cotton           2        3
16   4   Collar : Button-Down Collar           2        4
17   5               Pattern : Solid           2        5
20   6             Occasion : Formal           2        6
24  10                Fit : Slim Fit           2       10
36  19      Collar : Mandarin Collar           2       19

In [133]:
product_id=2
import numpy as np
specs['similarity']=np.zeros(len(specs))
for i in specs.index:
    specs.loc[i,'similarity']=specs.loc[product_id].dot(specs.loc[i])
specs.sort_values(by='similarity',ascending=False)[:7]['similarity']

id
2     7.0
3     5.0
10    2.0
32    2.0
31    2.0
1     1.0
33    1.0
Name: similarity, dtype: float64

In [134]:
addproduct[['id','desc']]

    id                                               desc
0    1  Allen solly Mens Cotton Full sleeve Overdyed s...
1    2  This classic shirt from Park Avenue is a versa...
2    3  Be noticed at work by enhancing your looks wit...
3    4  Wrangler is the everyday performance denim bra...
4    5  Mineral Glass Magnetic Resistant Shock Resista...
5    6  Mineral Glass Magnetic Resistant Shock Resista...
6    7  ACTIMOB MKTD Allen Solly Men's genuine leather...
7    8  Add a stylish touch to your look when you ador...
8    9  The navy blue propel EL mu idp is from the run...
9   10           Allen Solly Men's Plain Regular Fit Polo
10  11  Shop from a wide range of Top from GMI. Perfec...
11  12  The Vanca light blue top with a round neck at ...
12  13  Wrangler is the everyday performance denim bra...
13  14  This Anarkali Semi Stitched Gown is Made From ...
14  15  Technical information\r\n\r\nGeneral\r\nBrand ...
15  16  Keeping in mind her need for the perfect blend...
16  17  Campus sport shoes are premium quality light w...
17  18  Blue solid casual shirt with applique detail, ...
18  19  White and Blue striped casual shirt, has a spr...
19  20  Blue medium acid wash 5-pocket mid-rise jeans,...
20  21  Blue medium wash 5-pocket mid-rise jeans, mild...
21  22  Red printed woven regular top, has a shoulder ...
22  23  Navy Blue printed woven tiered top, has should...
23  24  Blue dark wash 5-pocket mid-rise jeans with em...
24  25  A pair of round-toe black and white printed fl...
25  26  A pair of round-toe black sneakers, has regula...
26  27  DETAILS\r\nSynthetic upper\r\nNon-marking rubb...
27  28  A pair of round-toe pink shimmer sneakers, has...
28  29  Educational Objective(s)\t"Fun with Words" is ...
29  30  Assembly Required\tNo\r\nBatteries Required\tN...
30  31  Maroon and black checked casual shirt, has a s...
31  32  Black and grey checked casual shirt, has a spr...
32  33  Brown printed T-shirt, has a round neck, short...

In [138]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

ds = addproduct[['id','desc']]

tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(ds['desc'])

cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

results = {}

for idx, row in ds.iterrows():
    similar_indices = cosine_similarities[idx].argsort()[:-100:-1]
    similar_items = [(cosine_similarities[idx][i], ds['id'][i]) for i in similar_indices]

    results[row['id']] = similar_items[1:]
    
print('done!')

def item(id):
    return ds.loc[ds['id'] == id]['desc'].tolist()[0].split(' - ')[0]

# Just reads the results out of the dictionary.
def recommend(item_id, num):
    print("Recommending " + str(num) + " products similar to " + item(item_id) + "...")
    print("-------")
    recs = results[item_id][:num]
    for rec in recs:
        print("Recommended: " + item(rec[1]) + " (score:" + str(rec[0]) + ")")

recommend(item_id=2, num=5)

done!
Recommending 5 products similar to This classic shirt from Park Avenue is a versatile style to own in your formal wardrobe. Cut from a cotton blend in a slim fit silhouette, the shirt is finished with a mandarin collar, a barrel cuff, a button placket, and full sleeves. Work it with lighter-hued tailored pants and leather shoes for a smart look....
-------
Recommended: Be noticed at work by enhancing your looks with this white formal shirt designed by Park Avenue. Made from 100% cotton, this slim-fit shirt features Ainsley collar, barrel cuff, and full sleeves. For a sophisticated look, you can pair it with beige, grey, navy blue or black trousers, leather shoes, and a belt.

 (score:0.17689917124825666)
Recommended: Maroon and black checked casual shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem

 (score:0.06065478061486408)
Recommended: White and Blue striped casual shirt, has a spread collar, long sleeves, button placket, and curved hem

Material & Care
Material: Cotton
Machine Wash (score:0.06043480567007861)
Recommended: Blue solid casual shirt with applique detail, has a spread collar, long sleeves, button placket, and curved hem

Material & Care
Material: 100% cotton
Machine Wash (score:0.057640426432625166)
Recommended: Black and grey checked casual shirt, has a spread collar, button placket, long sleeves with roll-up tabs, a chest pocket, curved hem

 (score:0.053011052183530076)

In [78]:
specifications[specifications['product_id']==]

Fit : Regular Fit               1
Sleeve Length : Long Sleeves    1
Material : Cotton               0
Collar : Button-Down Collar     0
Pattern : Solid                 0
                               ..
Sole Material:  TPR             0
Letter Recognition              0
Letter Sounds                   0
Spelling                        0
Reading Skills                  0
Name: 1, Length: 109, dtype: int64

In [74]:
specs.iloc[0]

Fit : Regular Fit               1
Sleeve Length : Long Sleeves    1
Material : Cotton               0
Collar : Button-Down Collar     0
Pattern : Solid                 0
                               ..
Sole Material:  TPR             0
Letter Recognition              0
Letter Sounds                   0
Spelling                        0
Reading Skills                  0
Name: 1, Length: 109, dtype: int64

In [63]:
type(specs.iloc[2])

pandas.core.series.Series

In [140]:
specs.loc[1]['Fit : Regular Fit']

1.0

In [141]:
events

Empty DataFrame
Columns: [id, timestamp, customer_id, event, product_id, transaction_id]
Index: []